import { VStack, Text, Container } from "@chakra-ui/react";
import TextLink from "src/Components/TextLink";

export default function License(): JSX.Element {
  return (
    <Container maxW="container.lg">
      <VStack mt={32} align="left">
        <Text fontSize="4xl">Terms and Conditions</Text>
        <Text fontSize="3xl">Algorithm / Website</Text>
        <Text>
          The license for the algorithms (a.k.a. the code) are distrubuted under{" "}
          <TextLink href="https://github.com/honungsburk/generative-studios/blob/master/LICENSE">
            GPLv3
          </TextLink>
          . Meaning that you can use the code for any purpose under a couple of
          conditions, the main one being that your work must be licensed under
          GPLv3 as well.
        </Text>
        <Text fontSize="3xl">Generated Media</Text>
        <Text>
          The media generated by the algorithms (a.k.a. imges, audio, video,
          etc) are distributed under{" "}
          <TextLink href="https://github.com/honungsburk/generative-studios/blob/master/LICENSE-FOR-GENERATED-MEDIA">
            CC-BY-4.0
          </TextLink>
          . In other words: you can do what ever you want with the generated
          content as long as you properly attribute them.
        </Text>
      </VStack>
    </Container>
  );
}
